# Generated by Django 3.2.14 on 2022-08-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('otp', models.CharField(default='', max_length=6)),
                ('otptime', models.CharField(default='174511', max_length=100)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('user_type_id', models.IntegerField(blank=True, default=None, null=True)),
                ('provider', models.CharField(choices=[('facebook', 'facebook'), ('google', 'google'), ('instagram', 'instagram'), ('twitter', 'twitter'), ('linkedin', 'linkedin'), ('usingemail', 'usingemail')], default=False, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
