# Generated by Django 3.2.14 on 2022-08-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20220823_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailotptime',
            field=models.CharField(default='145316', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='otptime',
            field=models.CharField(default='145316', max_length=100),
        ),
    ]
