# Generated by Django 3.2.14 on 2022-08-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20220823_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emailotptime',
            field=models.CharField(default='161348', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='otptime',
            field=models.CharField(default='161348', max_length=100),
        ),
    ]
