# Generated by Django 3.2.14 on 2022-08-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20220824_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailotptime',
            field=models.CharField(default='112616', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='otptime',
            field=models.CharField(default='112616', max_length=100),
        ),
    ]
