# Generated by Django 3.2.14 on 2022-08-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20220824_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='emailotptime',
            field=models.CharField(default='113001', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='otptime',
            field=models.CharField(default='113001', max_length=100),
        ),
    ]
