# Generated by Django 3.2.14 on 2022-08-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20220826_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailotptime',
            field=models.CharField(default='175626', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='otptime',
            field=models.CharField(default='175626', max_length=100),
        ),
    ]
