# Generated by Django 3.2.14 on 2022-08-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20220826_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailotptime',
            field=models.CharField(default='141537', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='otptime',
            field=models.CharField(default='141537', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
