# Generated by Django 3.2.14 on 2022-08-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(max_length=25)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('West Bengal', 'West Bengal')], max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('platform', models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Youtube', 'Youtube'), ('Pinterest', 'Pinterest'), ('Linkedin', 'Linkedin'), ('Pinterest', 'Pinterest'), ('Twitter', 'Twitter')], max_length=50)),
                ('other', models.CharField(max_length=50)),
                ('region_of_influence', models.CharField(choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('West Bengal', 'West Bengal')], max_length=70)),
                ('monetizing_audience', models.CharField(choices=[('Sponsered Blog Posts', 'Sponsered Blog Posts'), ('Sponsered Social media Posts', 'Sponsered Social media Posts'), ('Cost Per Action Ads', 'Cost Per Action Ads'), ('Cost Per Click Ads', 'Cost Per Click Ads'), ('Affiliate Programs', 'Affiliate Progams'), ('Not Currently Monetizing', 'Not  Currently Monetizing')], max_length=100)),
                ('monthly_earnings', models.FloatField(blank=True, default=False, null=True)),
                ('audience', models.CharField(choices=[('Gender(mainly)', 'Gender(mainly)'), ('Female', 'Femal'), ('Others', 'Others'), ('All', 'All')], max_length=14)),
                ('audience_age_range', models.CharField(choices=[('Gen Z(10-25)', 'Gen Z(10-25)'), ('Millennials(26-41)', 'Millennnials(26-41)'), ('Gen X(42-57)', 'Gen X(42-57)'), ('Boomers II(58-67)', 'Boomers II(58-67)')], max_length=100)),
                ('main_content_category', models.CharField(choices=[('Fashion', 'Fashion'), ('Lifestyle', 'Lifestyle'), ('DIY', 'DIY'), ('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('Music', 'Music'), ('Business', 'Business'), ('Beauty', 'Beauty'), ('Education', 'Education'), ('Health and Fitness', 'Health and Fitness'), ('Photography', 'Photography'), ('other', 'other')], max_length=100)),
            ],
        ),
    ]
