# Generated by Django 3.2.14 on 2022-08-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencer', '0002_influencerpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerpost',
            name='post_type_id',
            field=models.IntegerField(default=None),
        ),
    ]
