# Generated by Django 3.2.14 on 2022-08-18 07:27

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencer', '0003_influencerpost_post_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='follow',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=None, max_length=66, size=6),
        ),
    ]
