# Generated by Django 3.2.14 on 2022-08-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencer', '0008_auto_20220827_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='influencerstoryimage/'),
        ),
    ]
