# Generated by Django 3.2.14 on 2022-08-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('proof_of_employement', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('company_website', models.CharField(max_length=100)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('industry', models.CharField(max_length=100)),
                ('company_type', models.CharField(max_length=50)),
                ('company_size', models.CharField(max_length=50)),
                ('select_document', models.CharField(choices=[('Business Bank Statement', 'Business Bank Statement'), ('Business Licence', 'Business Licence'), ('Certificate of Incorporation', 'Certificate Of Incorporations'), ('Goods and ServiceTax Registration', 'Goods and ServiceTax Registration'), ('Permanent Account Number', 'Permanent Account Number'), ('Shop Establishment Certificate', 'Shop Establishment Certificate'), ('Udhog Aadhar', 'Udhog Aadhar'), ('Utility Bill', 'Utility Bill')], max_length=100)),
                ('upload_document', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='MessageBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='image1/')),
                ('sender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MessageInfluencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='image1/')),
                ('sender', models.CharField(max_length=500)),
            ],
        ),
    ]
